server:
  port: ${PORT:7001}
spring:
  datasource:
    url: ${STAGING_DB_URL}
    username: ${STAGING_DB_USERNAME}
    password: ${STAGING_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
app:
  jwt-secret: ${STAGING_JWT_SECRET}
